global:
  scrape_interval: 15s

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'alertmanagers'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9093']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
     module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets:
         - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'snmp_exporter'
    static_configs:
     - targets: ['192.168.0.1']
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116"      

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
